# Source: https://learn.microsoft.com/en-us/azure/container-instances/container-instances-github-action?tabs=openid
name: Build and push container to registry

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "mailgenninja/**"

env:
  APP_NAME: mailgenninja
  ACR_NAME: crmailgenninja
  ACR_RESOURCE_GROUP_NAME: rg-mailgenninja

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image
        id: build-image
        working-directory: mailgenninja
        run: |
          az acr build --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --resource-group ${{ env.ACR_RESOURCE_GROUP_NAME }} --image ${{ env.ACR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }} --registry ${{ env.ACR_NAME }} --file "Dockerfile" .
